import { Questionnaire } from "@/types/forms.types";
import {
  RECOMMENDATION_BUSINESS_OFFERING_FORM_DEFINITION,
  RECOMMENDATION_CONVERSION_FORM_DEFINITION,
  RECOMMENDATION_GENERAL_INFO_FORM_DEFINITION,
  RECOMMENDATION_MARKETING_FORM_DEFINITION,
  RECOMMENDATION_SYSTEMS_FORM_DEFINITION,
  VALUATION_FORM_DEFINITION,
} from "./forms.service";
import { routePaths } from "@/types/routes.enum";

export const VALUATION_QUESTIONNAIRE: Questionnaire = {
  forms: [VALUATION_FORM_DEFINITION],
};

export const RECOMMENDATION_GENERAL_INFO_QUESTIONNAIRE: Questionnaire = {
  forms: [RECOMMENDATION_GENERAL_INFO_FORM_DEFINITION],
  redirectPath: routePaths.RECOMMENDATION_BUSINESS_OFFERRING,
};

export const RECOMMENDATION_BUSINESS_OFFERING_QUESTIONNAIRE: Questionnaire = {
  forms: [RECOMMENDATION_BUSINESS_OFFERING_FORM_DEFINITION],
  redirectPath: routePaths.RECOMMENDATION_MARKETING,
};

export const RECOMMENDATION_MARKETING_QUESTIONNAIRE: Questionnaire = {
  forms: [RECOMMENDATION_MARKETING_FORM_DEFINITION],
  redirectPath: routePaths.RECOMMENDATION_CONVERSION,
};

export const RECOMMENDATION_CONVERSION_QUESTIONNAIRE: Questionnaire = {
  forms: [RECOMMENDATION_CONVERSION_FORM_DEFINITION],
  redirectPath: routePaths.RECOMMENDATION_SYSTEMS,
};

export const RECOMMENDATION_SYSTEMS_QUESTIONNAIRE: Questionnaire = {
  forms: [RECOMMENDATION_SYSTEMS_FORM_DEFINITION],
};

export enum QuestionnaireSlugs {
  VALUATION = "valuation",
  RECOMMENDATION_GENERAL_INFO = "general-info",
  RECOMMENDATION_BUSINESS_OFFERING = "business-offering",
  RECOMMENDATION_MARKETING = "marketing",
  RECOMMENDATION_CONVERSION = "conversion",
  RECOMMENDATION_SYSTEMS = "systems",
}

export const QUESTIONNAIRE_BY_SLUG: Record<string, Questionnaire> = {
  [QuestionnaireSlugs.RECOMMENDATION_GENERAL_INFO]:
    RECOMMENDATION_GENERAL_INFO_QUESTIONNAIRE,
  [QuestionnaireSlugs.RECOMMENDATION_BUSINESS_OFFERING]:
    RECOMMENDATION_BUSINESS_OFFERING_QUESTIONNAIRE,
  [QuestionnaireSlugs.RECOMMENDATION_MARKETING]:
    RECOMMENDATION_MARKETING_QUESTIONNAIRE,
  [QuestionnaireSlugs.RECOMMENDATION_CONVERSION]:
    RECOMMENDATION_CONVERSION_QUESTIONNAIRE,
  [QuestionnaireSlugs.RECOMMENDATION_SYSTEMS]:
    RECOMMENDATION_SYSTEMS_QUESTIONNAIRE,
  [QuestionnaireSlugs.VALUATION]: VALUATION_QUESTIONNAIRE,
};

export const RECOMMENDATION_QUESTIONNAIRE_SLUGS: string[] = [
  QuestionnaireSlugs.RECOMMENDATION_GENERAL_INFO,
  QuestionnaireSlugs.RECOMMENDATION_BUSINESS_OFFERING,
  QuestionnaireSlugs.RECOMMENDATION_MARKETING,
  QuestionnaireSlugs.RECOMMENDATION_CONVERSION,
  QuestionnaireSlugs.RECOMMENDATION_SYSTEMS,
];

export const RECOMMENDATION_QUESTIONNAIRES =
  RECOMMENDATION_QUESTIONNAIRE_SLUGS.map((slug) => QUESTIONNAIRE_BY_SLUG[slug]);

export const RECOMMENDATION_FORM_IDS = RECOMMENDATION_QUESTIONNAIRES.map(
  (q) => q.forms[0].id
);
