import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '../scss/variables.scss';
import '../scss/mixins.scss';
import '../scss/defaults.scss';
import '../scss/typography.scss';
import '../scss/open-color.scss';
import '../scss/material-theme.scss';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
